### ISSUE TITLE
Can't install actor

### ISSUE THREAD

**Issue by Garakros** [easly1989/ffxiv_actor#2]
Error message:

Exception not supported: System.ArgumentNullException: Value can't be zero.
Parameter name: gitHubApiUrl
   w Actor.Core.WebInteractions.ParseAssetFromGitHub(String gitHubApiUrl, Int32 assetIndex, Action onStart, Action onError)
   w ActorConsole.Program.Handle(WebInteractions webInteractions, SystemInteractions systemInteractions, Component component, CommandLineSwitches switches, String downloadTo, String installTo)
   w ActorConsole.Program.Main(String[] args)

**Comment by easly1989** [comment]
Must have written some garbage in the components file,
Gonna fix asap, sorry for the inconvenience >_<

**Comment by easly1989** [comment]
Should be fixed now,
you don't need to update the Actor, simply restart it and it should all go as expected ;)

let me know if there are other problems :)
