### ISSUE TITLE
Please don't enable "Simulate DoT crits" by default

### ISSUE THREAD

**Issue by ngld** [easly1989/ffxiv_actor#3]
That option is a debug option and doesn't improve the DPS results. It makes them more random actually. Here's the explanation from Ravahn:
> The Simulate Individual DoT Crits will add random variation into each DoT tick, but it can be useful for comparing min/max ranges to validate the DoT simulation.  that's why it is a debug option, but should generally be turned off.

**Comment by easly1989** [comment]
Should be ok running the program right now (as I updated the default configuration for the plugin)
sorry for the late answer, had a lot to do irl
